//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x360NANDManagerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x360NANDManagerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin rights are required for MMC functions....
        /// </summary>
        internal static string AdminRequiredForMMC {
            get {
                return ResourceManager.GetString("AdminRequiredForMMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to erase?! you&apos;ll lose EVERYTHING!
        ///If you do intend to erase Click on NO.
        /// </summary>
        internal static string EraseSafetyMessage {
            get {
                return ResourceManager.GetString("EraseSafetyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Device is not compatible with XSVF Flashing!.
        /// </summary>
        internal static string IncompatibleXSVF {
            get {
                return ResourceManager.GetString("IncompatibleXSVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files|*.log|Text Files|*.txt|All Files|*.*.
        /// </summary>
        internal static string LogFilter {
            get {
                return ResourceManager.GetString("LogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMC Functions are disabled... you need to start this program as admin to use them!.
        /// </summary>
        internal static string MMCDisabledNeedAdmin {
            get {
                return ResourceManager.GetString("MMCDisabledNeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted.
        /// </summary>
        internal static string OpAborted {
            get {
                return ResourceManager.GetString("OpAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with errors!.
        /// </summary>
        internal static string OpFailed {
            get {
                return ResourceManager.GetString("OpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        internal static string OpSuccess {
            get {
                return ResourceManager.GetString("OpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the dump....
        /// </summary>
        internal static string SelectDumpLocation {
            get {
                return ResourceManager.GetString("SelectDumpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File to write.
        /// </summary>
        internal static string SelectFileToWrite {
            get {
                return ResourceManager.GetString("SelectFileToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the log.
        /// </summary>
        internal static string SelectLogLocation {
            get {
                return ResourceManager.GetString("SelectLogLocation", resourceCulture);
            }
        }
    }
}
